dist: trusty
language: scala
scala:
   - 2.12.8
   - 2.11.8
jdk:
  - oraclejdk8
stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
jobs:
  include:
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ++$TRAVIS_SCALA_VERSION publishSigned