dist: trusty
jdk: oraclejdk8
language: scala
scala:
  - 2.13.4 # keep build.sbt crossScalaVersions synced with these versions, top version should be newest
  - 2.12.12 # keep build.sbt crossScalaVersions synced with these versions, top version should be newest
  - 2.11.12
stages:
  - name: test
  - name: release
    if: "branch = master AND type = push AND tag IS present AND tag =~ /^v[0-9].*$/ AND NOT fork"
jobs:
  include:
    - stage: release
      script: .travis/publish.sh
    - scala: "2.11.12"
      script: .travis/publish.sh

before_install:
  - openssl aes-256-cbc -K $encrypted_400f46935129_key -iv $encrypted_400f46935129_iv
    -in .travis/secret-key.asc.enc -out .travis/secret-key.asc -d
