# Much copied from sbt-github-actions, modified to support running e2e tests
name: Continuous Integration

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['master']

jobs:
  build:
    name: Build and Test
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        scala: [2.13.15, 2.12.20, 2.11.12]
        java: [temurin@1.21, temurin@1.17, temurin@1.11, temurin@1.8]
        experimental: [false]
        include:
          - os: ubuntu-latest
            scala: 2.13.15
            java: adopt@1.21
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}

      - name: Cache ivy2
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Cache coursier (linux)
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Cache sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Run tests
        run: sbt clean coverage test coverageReport
      - name: Coverage Aggregate
        run: sbt coverageAggregate

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
